version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: drf_cicd_pipeline
    volumes:
      - .:/app
    expose:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
