name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Test if the server is accessible via SSH using a password
    - name: Test server access with password
      run: |
        echo "Testing server access..."
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} 'echo "Connection successful"'
        
    # Build Docker image and deploy (example)
    - name: Build Docker image
      run: |
        docker build -t your-image-name .
    
    - name: Push Docker image to registry (optional)
      run: |
        docker push your-image-name
    
    # Deploy application
    - name: Deploy to server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} 'docker-compose -f /path/to/docker-compose.yml up -d'
