name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub or other registry
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t setu0123/drf_cicd_pipeline:latest .
          docker push setu0123/drf_cicd_pipeline:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Wait for the build job to complete

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy private SSH key to access EC2
      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      # Deploy to EC2
      - name: Deploy application to EC2
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          # Pull the latest image
          docker pull setu0123/drf_cicd_pipeline:latest
          
          docker-compose -f /home/ubuntu/drf_cicd_pipeline/docker-compose.yml down || true
          docker-compose -f /home/ubuntu/drf_cicd_pipeline/docker-compose.yml up -d --build
